### ISSUE TITLE
Anonymous mode is not fully anonymous

### ISSUE THREAD

**Issue by sanaerosen-yelp** [kedarv/votey#24]
People might want an extra anonymous mode where votes are not stored in the database (with the tradeoff being reduced functionality)

**Comment by kedarv** [comment]
I've added --secret which obscures the author, and --explode is in progress (will delete polls after X minutes).

I don't think not storing things in DB is worth it, mainly because it's still "fake trust". While --secret still stores data, it obscures the author name. If you don't trust votey enough that --secret isn't "secret" enough (ie. you want to bypass data storage), you'd still need to trust that --super-extra-anonymous actually does that. And there's really no way to verify that as an end user.
